### ISSUE TITLE
App icon also for notifications

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/quota_warning#1]
Maybe something like a HDD/floppy disk with an exclamation mark on it?

**Comment by nickvergessen** [comment]
@jancborchardt can you help with an icon?

**Comment by MariusBluem** [comment]
https://github.com/nextcloud/server/blob/27690e0fb49cb783e98bd261471ae44aded786a4/apps/files/img/quota.svg

**Comment by jancborchardt** [comment]
Right, the one I added there can be used. :)

**Comment by nickvergessen** [comment]
Can't get it to view properly, can you create a white 32*32 version?
