### ISSUE TITLE
Issue with Quota and photos

### ISSUE THREAD

**Issue by waylenwasywas** [nextcloud/quota_warning#133]
### Steps to reproduce
1. enable auto photo backup
2. backup photos from mobile client
3. look at quota change

### Expected behaviour
The used quota should increase based on size 

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system**:

**Web server:**
Almalinux 8.6
**Database:**
MariaDB
**PHP version:**
8.1
**Nextcloud version:** (see Nextcloud admin page)
25
**Where did you install Nextcloud from:**
Official Website

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
https://pastebin.com/CVzadWA3
**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
https://pastebin.com/x0WsW8ZL
or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

### Client configuration
**Browser:**

**Operating system:**

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by nickvergessen** [comment]
This app only shows the quota that the system maintains. It does not record or keep track of a quota.

As a general comment, as far as I know the quota is cached for some minutes so that could be the answer to your issue.

**Comment by nickvergessen** [comment]
I hope this solved your issue.
