### ISSUE TITLE
Notifications are sent without translation

### ISSUE THREAD

**Issue by ak47d** [nextcloud/quota_warning#191]
Quota warning	1.18.0
Nextcloud 27.1.5

The Nextcloud config.php contains the following locale settings:
'default_language'
'default_phone_region'
  'default_locale'

But notifications
quota_warning is still sent in English.

The required locale is present in the l10n application directory

**Comment by nickvergessen** [comment]
It's translated in the user's language. The default language from config.php does not matter.
Check the database:
```
SELECT * FROM oc_preferences WHERE appid = 'core' AND configkey = 'lang';
```

Or if it's your user you can also check the selected language in `/index.php/settings/user`

**Comment by ak47d** [comment]
Thanks for the quick response. I made a request to the database, all users have the same locale - ru

**Comment by nickvergessen** [comment]
Works fine here:
![grafik](https://github.com/nextcloud/quota_warning/assets/213943/89fd7d2f-d79a-4da7-afe9-60130e2edb27)
