### ISSUE TITLE
Quota Warning - Kontingenteinstellungen

### ISSUE THREAD

**Issue by Lurchi01** [nextcloud/quota_warning#34]
Hi,

ich weiß nicht, ob ich hier richtig bin. Versuchs einfach mal:

What does the setting “Link to quota management” doing? What should I fill in?

Hat da jemand eine Antwort dazu?

Danke
Volker

**Comment by nickvergessen** [comment]
The setting is focusing on providers mostly. So if they can manage the quota e.g. on your website by upgrading the booked plan. If you don't have anything like that, just leave it empty.
