### ISSUE TITLE
Nextcloud 19 compatibility

### ISSUE THREAD

**Issue by ntimo** [nextcloud/quota_warning#53]
### Steps to reproduce
1. Update to Nextcloud 19
2. Go to Settings --> Apps
3. The app is deactivated because it does not Support Nextcloud 19

### Expected behaviour
The app should support Nextcloud 19

### Actual behaviour
It only supports Nextcloud 18

### Server configuration
**Nextcloud version:** 19.0.0

**Where did you install Nextcloud from:**
self build nextcloud 19 docker image

**Comment by nickvergessen** [comment]
I published 1.7.0 around that time, check it again please.
