### ISSUE TITLE
Quota warning error

### ISSUE THREAD

**Issue by systemcarrotpt** [nextcloud/quota_warning#57]
I recently upgraded NC to v20, there is a user that should have received a quota alert but he has not, also theres an error in a PHP function. The error is:
TypeError: Argument 2 passed to OCA\QuotaWarning\CheckQuota::shouldIssueWarning() must be of the type int, string given, called in /var/www/html/custom_apps/quota_warning/lib/CheckQuota.php on line 110

Maybe this can help:
this function is receiving a string in the level variable:
protected function shouldIssueWarning(string $userId, int $level): bool {

this is the line thats causing the problem i think:
if ($this->shouldIssueWarning($userId, 'warning')) {

I dont know if this error was present in v19, because there was no user excedig minimum quota warning. 

### Steps to reproduce
1. Upload file from a user up to a minimum quota warning level
2. No alert is shown
3. Errors show up in NC log

### Expected behaviour
A warning should be shown to the user

### Actual behaviour
Nothing is happening

### Server configuration
**Operating system**: Raspbian OS

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.4.11

**Nextcloud version:** 20.0.0

**Where did you install Nextcloud from:** Docker container from Docker Hub

I dont think if its needed all the information about my system for this bug, so im not posting for now, but if its needed i can provide it later.

**Comment by nickvergessen** [comment]
Can you post the full line from nextcloud.log file?

**Comment by systemcarrotpt** [comment]
Hi, my log has rotated and for some reason i cant load it in Nextcloud so, im posting the unformatted json error from the logfile.

I replaced some info that i think is sensitive.

`{
    "reqId": "REQID",
    "level": 3,
    "time": "2020-10-11T15:55:08+00:00",
    "remoteAddr": "",
    "user": "--",
    "app": "core",
    "method": "",
    "url": "--",
    "message": {
        "Exception": "TypeError",
        "Message": "Argument 2 passed to OCA\\QuotaWarning\\CheckQuota::shouldIssueWarning() must be of the type int, string given, called in /var/www/html/custom_apps/quota_warning/lib/CheckQuota.php on line 110",
        "Code": 0,
        "Trace": [{
                "file": "/var/www/html/custom_apps/quota_warning/lib/CheckQuota.php",
                "line": 110,
                "function": "shouldIssueWarning",
                "class": "OCA\\QuotaWarning\\CheckQuota",
                "type": "->",
                "args": ["USERNAME", "warning"]
            }, {
                "file": "/var/www/html/custom_apps/quota_warning/lib/Job/User.php",
                "line": 43,
                "function": "check",
                "class": "OCA\\QuotaWarning\\CheckQuota",
                "type": "->",
                "args": ["USERNAME"]
            }, {
                "file": "/var/www/html/lib/private/BackgroundJob/Job.php",
                "line": 52,
                "function": "run",
                "class": "OCA\\QuotaWarning\\Job\\User",
                "type": "->",
                "args": [{
                        "uid": "USERNAME"
                    }
                ]
            }, {
                "file": "/var/www/html/lib/private/BackgroundJob/TimedJob.php",
                "line": 59,
                "function": "execute",
                "class": "OC\\BackgroundJob\\Job",
                "type": "->",
                "args": [{
                        "__class__": "OC\\BackgroundJob\\JobList"
                    }, {
                        "__class__": "OC\\Log"
                    }
                ]
            }, {
                "file": "/var/www/html/cron.php",
                "line": 126,
                "function": "execute",
                "class": "OC\\BackgroundJob\\TimedJob",
                "type": "->",
                "args": [{
                        "__class__": "OC\\BackgroundJob\\JobList"
                    }, {
                        "__class__": "OC\\Log"
                    }
                ]
            }
        ],
        "File": "/var/www/html/custom_apps/quota_warning/lib/CheckQuota.php",
        "Line": 262,
        "CustomMessage": "Error while running background job (class: OCA\\QuotaWarning\\Job\\User, arguments: Array\n(\n    [uid] => USERNAME\n)\n)"
    },
    "userAgent": "--",
    "version": "20.0.0.9"
}`

Thanks

**Comment by nickvergessen** [comment]
That's good enough.

Formated version:
```json
{
  "reqId": "REQID",
  "level": 3,
  "time": "2020-10-11T15:55:08+00:00",
  "remoteAddr": "",
  "user": "--",
  "app": "core",
  "method": "",
  "url": "--",
  "message": {
    "Exception": "TypeError",
    "Message": "Argument 2 passed to OCA\\QuotaWarning\\CheckQuota::shouldIssueWarning() must be of the type int, string given, called in /var/www/html/custom_apps/quota_warning/lib/CheckQuota.php on line 110",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/html/custom_apps/quota_warning/lib/CheckQuota.php",
        "line": 110,
        "function": "shouldIssueWarning",
        "class": "OCA\\QuotaWarning\\CheckQuota",
        "type": "->",
        "args": [
          "USERNAME",
          "warning"
        ]
      },
      {
        "file": "/var/www/html/custom_apps/quota_warning/lib/Job/User.php",
        "line": 43,
        "function": "check",
        "class": "OCA\\QuotaWarning\\CheckQuota",
        "type": "->",
        "args": [
          "USERNAME"
        ]
      },
      {
        "file": "/var/www/html/lib/private/BackgroundJob/Job.php",
        "line": 52,
        "function": "run",
        "class": "OCA\\QuotaWarning\\Job\\User",
        "type": "->",
        "args": [
          {
            "uid": "USERNAME"
          }
        ]
      },
      {
        "file": "/var/www/html/lib/private/BackgroundJob/TimedJob.php",
        "line": 59,
        "function": "execute",
        "class": "OC\\BackgroundJob\\Job",
        "type": "->",
        "args": [
          {
            "__class__": "OC\\BackgroundJob\\JobList"
          },
          {
            "__class__": "OC\\Log"
          }
        ]
      },
      {
        "file": "/var/www/html/cron.php",
        "line": 126,
        "function": "execute",
        "class": "OC\\BackgroundJob\\TimedJob",
        "type": "->",
        "args": [
          {
            "__class__": "OC\\BackgroundJob\\JobList"
          },
          {
            "__class__": "OC\\Log"
          }
        ]
      }
    ],
    "File": "/var/www/html/custom_apps/quota_warning/lib/CheckQuota.php",
    "Line": 262,
    "CustomMessage": "Error while running background job (class: OCA\\QuotaWarning\\Job\\User, arguments: Array\n(\n [uid] => USERNAME\n)\n)"
  },
  "userAgent": "--",
  "version": "20.0.0.9"
}
```

The fix should be the following:
https://github.com/nextcloud/quota_warning/pull/58/files#diff-9b24eeb8fed24e0f7c5552c5644ebe8bL259-R253

Remove red lines and add green lines

**Comment by systemcarrotpt** [comment]
Hi again.

I will be waiting for the fix instead of fixing the php code.

Thanks 👍

**Comment by nickvergessen** [comment]
Thanks anyway for reporting!

New version is in the appstore: https://apps.nextcloud.com/apps/quota_warning/releases?platform=20#20
