### ISSUE TITLE
What is quota ?

### ISSUE THREAD

**Issue by pierr0t** [nextcloud/quota_warning#63]
Hello,
Question might seem stupid but ... I want to give users let's say a 200gb quota. The occupancy as displayed by Nextcloud seems to only take real files into account without versions and without files in the trash so I am/was in the situation of user telling he had only 120gb on the cloud while the real disk occupancy was already above 200gb. I cleaned everything to have him back to work and started searching for some kind of warning so he does not end up stuck.
This app seems to really be the solution but I am back to the first question because I cannot find this info ... what does Nextcloud display (just visible files or visible+versions+trash) and what does this application calculate, just files or files+versions/trash ?
And the next question (or maybe enhancement request) would be to have the app warn against full size of user account (files+versions+trash) because at the end the problem is really here: I need to be sure that the user does not go over the real quota, disk space ... 
Thks !
Pierre

**Comment by nickvergessen** [comment]
See https://docs.nextcloud.com/server/stable/user_manual/en/files/quota.html

Otherwise I recommend to google a bit or ask for help in the forum.
In fact I don't know a more accurate answer myself as I just take the values the API gives me and generate the notification if it is above the threshold.

**Comment by pierr0t** [comment]
Hello
Thanks for your answer and for that link I didn't find. I already asked the question here: https://help.nextcloud.com/t/how-much-space-is-left/2893/4 , no luck so far. To be frank, I don't understand what's the use of the existing quota when 120gb of files ends up occupying 250gb, that info does not help anybody unless I don't understand something ...
Anyway in that context, your app is very helpful :-)
Pierre.

**Comment by nickvergessen** [comment]
Well you can adjust the retention of versions and trashbin to 0, or you just calculate in the doubling of them to nail the quota.
