### ISSUE TITLE
Quota Warning for GroupFolders

### ISSUE THREAD

**Issue by Nyco** [nextcloud/quota_warning#64]
My doubts:
1. Does this make sense?
2. Is this the right place?

### Steps to reproduce
1. Create a Group Folder
2. Setup a quota
3. Fill the folder

### Expected behaviour
There should be a warning

### Actual behaviour
There does not seem to be any such feature

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Where did you install Nextcloud from:**

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

### Client configuration
**Browser:**

**Operating system:**

#### Nextcloud log (data/owncloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by nickvergessen** [comment]
Well this app currently operates on a per user basis.
Which user should be notified in case the limit is being reached?
Also I don't think there is an public API for this, so it would need to be handled by the groupfolder app for now.

**Comment by SimJoSt** [comment]
Just searched for the exact same feature, as users contact us when sync and document editing doesn't work, without realizing their storage quota is reached.
I would have suggested contacting group folder admins, if they are set and all group folder users, as a fallback.

However, if there is no API to do this, then it is pointless to chat about it :)
Maybe I will raise this in the group folder repo.
