### ISSUE TITLE
Email notification not working

### ISSUE THREAD

**Issue by adripo** [nextcloud/quota_warning#65]
### Steps to reproduce
1. Go to Additional settings as admin user
2. Click on any `Send an email` checkbox
3. --> `Saved!` popup appears on top
4. Reload page (optional, to see checkbox status)

### Expected behaviour
* Checked checkboxes remain checked
* Email sent if quota is exceeded

### Actual behaviour
All checkboxes are unchecked
email is not sent if quota is exceeded

### Server configuration
Nextcloud v21.0
Installed with docker compose, that can be found here
https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/with-nginx-proxy/postgres/apache

**Operating system**:
docker

**Web server:**
apache

**Database:**
postgres

**PHP version:**
8 (not sure, the one provided in the image)

**Nextcloud version:** (see Nextcloud admin page)
21.0.0.18

**Where did you install Nextcloud from:**
https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/with-nginx-proxy/postgres/apache

**List of activated apps:**

- Accessibility	1.7.0	
- Activities for shared file downloads	1.10.0		
- Activity	2.14.3	
- AppOrder	0.12.0		
- Breeze Dark	21.0.5		
- Calendar	2.1.3	
- Camera RAW Previews	0.7.10		
- Comments	1.11.0	
- Contacts	3.5.1	
- Contacts Interaction	1.2.0	
- Dashboard	7.1.0	
- Deleted files	1.11.0	
- File sharing	1.13.1	
- Forms	2.2.2	
- Log Reader	2.6.0	
- Metadata	0.13.0		
- Monitoring	1.11.0	
- Music	1.0.3		
- Nextcloud announcements	1.10.0	
- Notes	4.0.4	
- Notifications	2.9.0	
- Notifications for calendar event updates	1.2.0		
- Password policy	1.11.0	
- PDF viewer	2.1.0	
- Photos	1.3.0	
- Polls	1.7.5		
- Privacy	1.5.0	
- Quota warning	1.10.0		
- Recommendations	1.0.0	
- Right click	1.0.0	
- Share by mail	1.11.0	
- Splash	1.2.2		
- Talk	11.1.1	
- Tasks	0.13.6	
- Text	3.2.0	
- Theming	1.12.0	
- Update notification	1.11.0	
- User status	1.1.1	
- Versions	1.14.0	
- Video player	1.10.0	
- Weather status

**Nextcloud configuration:**

{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "overwritehost": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": true,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "21.0.0.18",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_phone_region": "***REMOVED SENSITIVE VALUE***",
        "simpleSignUpLink.shown": false
    }
}

### Client configuration
**Browser:**
any

**Operating system:**
windows

#### Nextcloud log (data/owncloud.log)
```
Insert your Nextcloud log here
```

#### Browser log

When pressing a checkbox to ENABLE it

```
a) The javascript console log
globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.

b) The network log
fetch("https://website.com/ocs/v2.php/apps/provisioning_api/api/v1/config/apps/quota_warning/info_email", {
  "headers": {
    "accept": "*/*",
    "accept-language": "en-US,en;q=0.9;q=0.8",
    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
    "ocs-apirequest": "true",
    "requesttoken": "**TOKEN**",
    "sec-ch-ua": "\"Google Chrome\";v=\"89\", \"Chromium\";v=\"89\", \";Not A Brand\";v=\"99\"",
    "sec-ch-ua-mobile": "?0",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "x-requested-with": "XMLHttpRequest"
  },
  "referrerPolicy": "no-referrer",
  "body": "value=no",
  "method": "POST",
  "mode": "cors",
  "credentials": "include"
});
```

**Comment by adripo** [comment]
I think I found out the problem.
Looking at the network log I see that the body of the request is always `value=no`.

**Comment by adripo** [comment]
According to jquery documentation checked value cannot be done with `.attr`, but `.prop` method must be used

https://api.jquery.com/attr/
> As of jQuery 1.6, the .attr() method returns undefined for attributes that have not been set. To retrieve and change DOM properties such as the checked, selected, or disabled state of form elements, use the .prop() method.

**Comment by julian70400** [comment]
Why is it closed if the bug still occurs ?
