### ISSUE TITLE
Feature request - Email notification

### ISSUE THREAD

**Issue by MeCias** [nextcloud/quota_warning#8]
Thanks a lot for the app. Was playing around with some quotas and it worked flawlessly. 

It would be nice if the app could additionaly send a email notification to the user as well. On one of the 3 percentages or even all of them.

**Comment by nickvergessen** [comment]
I don't want to duplicate this really. We will soon have push notifications on the mobile clients. This together with the desktop client already creating desktop notifications for the feature should be enough from my pov.

**Comment by MeCias** [comment]
I here you. I was thinking more about those, like me ;), they are not using the nextcloud tools. Those who are just happy with any webdav implementation of the OS or tool they are using.
But you are right, too much of the same information on different places would be too much.
