### ISSUE TITLE
Please add compatibility with Nextcloud V23

### ISSUE THREAD

**Issue by leonardohlee** [nextcloud/quota_warning#84]
Please add compatibility with Nextcloud V23

**Comment by digitalcircuit** [comment]
The latest code [appears to be enabled for Nextcloud versions up to v24](https://github.com/nextcloud/quota_warning/commit/0c1980f8358b316c2877a7fb8518476cad788539#diff-ab97a56738913a50d2334c4d3f10991748d3e29d011f5a674734b63d33d5ce9eR26), there just hasn't been a [release to the Nextcloud app store yet](https://apps.nextcloud.com/apps/quota_warning).

As Nextcloud v23 was just released, hopefully this will be done soon!

(I was surprised the Nextcloud v23 update notification didn't wait until I had compatible app versions; I'll check more closely next time.)

**Comment by leonardohlee** [comment]
Thank you!
