### ISSUE TITLE
Set custom quota warning values

### ISSUE THREAD

**Issue by sunjam** [nextcloud/quota_warning#9]
Is this already an option?  I'd like to set my own quota values rather than use the default.

**Comment by nickvergessen** [comment]
Which value would you choose?

**Comment by sunjam** [comment]
I'd just like to set any number I want.  Perhaps the current numbers are
the sane default, which can be changed under admin settings.

**Comment by AceSlash** [comment]
I think that a 50% warning is not that useful, at least for me.

**Comment by nickvergessen** [comment]
Feel free to change the values here:
https://github.com/nextcloud/quota_warning/blob/master/lib/CheckQuota.php#L33-L35

**Comment by nickvergessen** [comment]
Maybe we change the values to 80, 90 and 95?

**Comment by seimsel** [comment]
I think it would be very useful if it was possible to configure an arbitrary number of warnings at custom values. Maybe it could even be changed by the user instead of the admin? Or even better: An option for the admin to allow the users to change it from the default, which the admin decides.

My opinion on a default value would be 80 and 95. But I think we will find endless opinions on that.

**Comment by nickvergessen** [comment]
Yeah, I see that problem, that's why I'm open for 2 things:

1. Adjust existing numbers to something useful
2. Allow admins to specify 3 numbers.

**Comment by AceSlash** [comment]
Best of the best would be to specify the number of alerts and the % for each. In my case, I know that my users will simply ignore a warning if it says something else than 95%, so a single alert is sufficient for me.

But of course it depends on so many things that you simply can't have a single policy for everyone.

**Comment by Schmuuu** [comment]
I agree with @AceSlash and also think it would be awesome (best solution?) if the users can define the values for themselves, or the admin can set the values per user/ group.

The idea to "Adjust existing numbers to something useful" isn't a good approach in my opinion.
Users with 1GB storage and 75% used space don't have much space left and a warning may be applicable. For users with 500 GB storage even a 90% quota warning is rather nice to know than an actual alert to them.

For admins that have great diversity in the defined quotas, it is difficult to chose the right percentage to notify.

**Comment by Gardakant** [comment]
While changing values in checkQuota.php is a solution it's a bad one: this generates a Security & Configuration problem :)

root@host1:/var/www/nextcloud# sudo -u www-data php occ integrity:check-app quota_warning
  - INVALID_HASH:
    - lib/CheckQuota.php:
      - expected: d54a8e91ded58799ca71aeda7c51b0e9fb286aea126f15321b1798f2f204b2376bfb3c0710b9b6a09c40fecc0c0998ce8867cbdec6920b7932ee9800face1bdf
      - current: da7479000fbce371208e718b4bdec9216373d92444dc71e8c8ba6295310cd4dc2885585bf9de0aaa7df36b3955d60462910d29bcb4c2bbdf52ba3c87eac8f470
root@host1:/var/www/nextcloud#

**Comment by JK74** [comment]
I do agree with Schmuuu his posting! Maybe allow some settings on this like below 90% by the user? and a setting like 90 or 95% by the admin? What about notifications? Do we get them on e-mail as well (not existing today)? thnx

**Comment by DJCrashdummy** [comment]
to address @Schmuuu's problem with _great diversity in the defined quotas_ (https://github.com/nextcloud/quota_warning/issues/9#issuecomment-320230342), maybe it will make sense to add a value (in MB/GB/etc.) which must be undershot first to trigger a warning-action; maybe one value overall or different ones for every percentage...

but the whole thing would make it more and more complicated. - _...i'm just thinking aloud._
